### PR TITLE
Optional NetworkManager, ModemManager, Colord

### PR DESCRIPTION
**Pull request by filakhtov**
Hi from the Gentoo user!

I've created a set of patches to be able to disable ModemManager while keeping NetworkManager and network panel working and also Colord (patch from Gentoo) during configure / building stages.

Would be great if you could merge and adopt changes for the next release as it gives better control over build deps.

Thanks in advance!

### CODE REVIEW

**Comment by clefebvre** [comment]
Thanks, this should go in early in 3.2.

**Comment by clefebvre** [comment]
Hi,

I'm getting the following error when building (modemmanager support is enabled):

cc-network-panel.c:52:24: fatal error: libmm-glib.h: No such file or directory
compilation terminated.
Makefile:631: recipe for target 'cc-network-panel.lo' failed
make[6]: *** [cc-network-panel.lo] Error 1
make[6]: *** Waiting for unfinished jobs....
net-device-mobile.c:37:24: fatal error: libmm-glib.h: No such file or directory
compilation terminated.
Makefile:631: recipe for target 'net-device-mobile.lo' failed
make[6]: *** [net-device-mobile.lo] Error 1
In file included from /usr/include/glib-2.0/gobject/gobject.h:28:0,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from net-device-team.c:24:

**Comment by filakhtov** [comment]
Which distro is it? For ubuntu-like ones you need libmm-glib-dev (https://developer.gnome.org/libmm-glib/0.7/)

**Comment by filakhtov** [comment]
Hey @clefebvre, I've rebased my branch to resolve conflict. What is the status? Could that be merged finally, pretty please?

**Comment by joakim-tjernlund** [comment]
This change would be very welcome

**Comment by clefebvre** [comment]
Hi,

I still have the same issue with it.

I've got libmm-glib-dev installed though.. 

`libmm-glib-dev:amd64: /usr/include/libmm-glib/libmm-glib.h`

**Comment by filakhtov** [comment]
@clefebvre: Thanks for update. Could you, please, provide a list of options your are using for `configure`? I will double-check and try to fix an issue!

**Comment by filakhtov** [comment]
Hey, @clefebvre, I've debugged and fixed the problem. Sorry for the inconveniences. Everything should be fixed now. Please, retest and let's finally merge it 🙏 Thanks in advance!

**Comment by clefebvre** [comment]
@filakhtov thanks for your efforts and patience. This is finally getting in. Sorry it took so long.

**Pull request merged**
