### PR TITLE
Improve debian packaging

### PR DESCRIPTION
**Pull request by Fantu**

### CODE REVIEW

**Comment by clefebvre** [comment]
Please remove Breaks: cinnamon (<< 3.4), cinnamon-core (<< 3.2), gnome-power-manager (<< 3.0).

**Comment by Fantu** [comment]
@clefebvre break gnome-power-manager was already present, and about them should not cause problem but solves where the cases happen, apt will solves before with break present instead fails on packages install conflict
another question: gnome-icon-theme and gnome-icon-theme-symbolic are really needed?

**Comment by clefebvre** [comment]
Hi Fantu,

It was never added though, it was inherited by gnome-control-center 3.x, it's pretty ancient, maybe it's time we get rid of it.

No need to add new breaks either unless a clear conflict is identified.

Regarding the icon themes, I'm not sure why we depend on them. I'd suggest to remove the deps.

**Comment by Fantu** [comment]
Ok, gnome-control-center <3.0 is really old, I'll remove it from break, I'll remove also icon theme already removed in debian package (based on this I suppose should not cause problem).
Now I'll rebase the PR

**Comment by clefebvre** [comment]
You still have

`Breaks: cinnamon (<< 3.4), cinnamon-core (<< 3.2)`

Why are these necessary?

**Comment by Fantu** [comment]
was add by maxy, I suppose it spotted possible conflicts in upgrades testing, I not tried cinnamon upgrade without them but I suppose mazy not added unneeded things, is an expert debian developer

**Comment by clefebvre** [comment]
That looks specific to Debian to me.

On our side cinnamon-core is a metapackage and its version is 2017.06.02.

**Comment by clefebvre** [comment]
We also have no conflict between ccc 3.4 and cinnamon 3.2.

**Comment by Fantu** [comment]
if you want remove them

**Comment by clefebvre** [comment]
Yes please.

**Comment by Fantu** [comment]
done
I also spotted a CANBERRA_REQUIRED_VERSION=0.13 in configure.ac I suppose needs to be removed, I saw it was already removed in debian control for version 3.0 and removed files that use it but not in configure, that I suppose it make build in clean enviroment to fails (I'll check), linux mint packages are not build in clean enviroment? In any case this will be out of this PR

**Comment by Fantu** [comment]
@clefebvre I tested clean build for next debian experimental packages and built successfull, no configure change seems required about canberra.
In the log I spotted shlibsdeps warning about possible uneeded deps but will need investigation and in any case in other PR.

**Comment by clefebvre** [comment]
Canberra was used to play the test sounds. The sound module was rewritten in Python and moved to Cinnamon so that dependency isn't needed anymore.

It's not really a dep in configure.ac, just a variable that was left there by mistake. I'll remove it now in a commit.

**Pull request merged**
