### PR TITLE
Port to libnm >= 1.2, obsoleting legacy nm-glib

### PR DESCRIPTION
**Pull request by besser82**
This is based on the files in gnome-control-center v3.24.2

### CODE REVIEW

**Comment by besser82** [comment]
See https://github.com/linuxmint/cinnamon-control-center/issues/164.

**Comment by besser82** [comment]
Ready for review / testing…

**Comment by clefebvre** [comment]
Maybe in 3.6.. we still need to support Betsy/Jessie for this release.

**Comment by khurshid-alam** [comment]
@besser82 @clefebvre 

Hi, Unity maintainer here. Sorry for asking here like this. But I don't know any other way to contact you. unity-control-center is also a fork of g-c-c which is still using old libnm-glib. Is it ok to use the port from here? 

I like to stay with old notebook style for nm connection editors. And I see cinnamon is also doing the same. The way I see it this port was based on g-c-c-3.24. 

We are on [ubuntu-community](https://community.ubuntu.com/c/desktop/ubuntu-unity-dev). Thanks.

**Comment by clefebvre** [comment]
Sorry for the late reply @khurshid-alam (I don't really follow my gh notifications). Yes, anything that can help is fine with us.

**Pull request merged**
