### PR TITLE
network: Add support for displaying DNS6 parameters

### PR DESCRIPTION
**Pull request by treysis**
Implements #233

### CODE REVIEW

**Comment by treysis** [comment]
Can somebody review and/or merge this?

**Comment by ItzSwirlz** [comment]
I give a yes on it but wouldn't put a yea or nay on it, due to my lack of understanding /shrug

Hopefully this gets merged before 5.0.0

**Comment by treysis** [comment]
I think an OS that considers itself superior in networking should have proper support for IPv6. Windows can do this since XP out of the box. The famous Linux desktops should support it as well.

**Comment by treysis** [comment]
Anybody else willing to review or comment on this?

**Comment by collinss** [comment]
@treysis it may take a while, but someone will get to it eventually. We're a small team of mostly volunteers, and some of us have very limited or no experience with dns6. Plus we just released Mint 20.1 and there were a couple of fairly serious issues from that that need to be addressed quickly, so the ones who are mostly likely to be able to help you are currently dealing with more urgent matters.

**Comment by treysis** [comment]
Ah yes, you're right. And those not occupied might want to relax a few days after pushing the release :)

That said, this PR doesn't do anything to the DNS6 configuration. It will only _display_ the current configuration as reported by `NetworkManager`.

**Comment by treysis** [comment]
How about now ^^

**Comment by mtwebster** [comment]
Works fine

Thanks!

**Pull request merged**
