### PR TITLE
Meson

### PR DESCRIPTION
**Pull request by Salamandar**
Replaces #210  (I had deleted my fork, Github can't re-link the PR)

### CODE REVIEW

**Comment by Fantu** [comment]
in debian/rules: why you removed these lines?
export DEB_BUILD_MAINT_OPTIONS  = hardening=+all
export DEB_CFLAGS_MAINT_APPEND  = -Wall -pedantic
export DEB_LDFLAGS_MAINT_APPEND = -Wl,--as-needed
DEB_HOST_MULTIARCH ?= $(shell dpkg-architecture -qDEB_HOST_MULTIARCH)
DATA_PKG = cinnamon-control-center-data
MAIN_PKG = cinnamon-control-center

the latest 3 are needed to be not undefined

about "No such file or directory at /usr/bin/dh_gnome_clean line 67." is strange, in debian/control gnome-pkg-tools is present in the build-dep.

**Comment by Salamandar** [comment]
> in debian/rules: why you removed these lines?
> export DEB_BUILD_MAINT_OPTIONS = hardening=+all
> export DEB_CFLAGS_MAINT_APPEND = -Wall -pedantic
> export DEB_LDFLAGS_MAINT_APPEND = -Wl,--as-needed
> DEB_HOST_MULTIARCH ?= $(shell dpkg-architecture -qDEB_HOST_MULTIARCH)
> DATA_PKG = cinnamon-control-center-data
> MAIN_PKG = cinnamon-control-center
> 
> the latest 3 are needed to be not undefined

OK, I inspired myself from Nemo where those variables did not exist. I'll put them back.

**Comment by Fantu** [comment]
debian/ changes seems now ok from a fast look, thanks.
about circleci commit is not needed anymore
I think is probably good also remove the old build system and keep and meson

**Comment by mtwebster** [comment]
I committed this manually - there were a couple of build issues and the last commit wasn't necessary anymore.

I did a further commit doing some additional clean up (and build issues due to the age of this pr). It got attributed to @Salamandar instead of me - something from all the rebasing I was doing - it makes no difference to me, I just wanted to apologize for accidentally sticking your name on something that wasn't yours.

I tried to get rid of a number of files we don't require for how we use this package - hopefully I got it all.

Thanks a lot

**Pull request closed without merging**
