### PR TITLE
Add support for online-accounts

### PR DESCRIPTION
**Pull request by besser82**
This PR adds optional integration for gnome-online-accounts into cinnamon-settings.

This comes in handy, if you want to use gDrive from Nemo or automatically renew your Kerberos credentials for some services.

Ported from gnome-controll-center 3.24.X branch.

***

These PRs are needed for this feature:

* https://github.com/linuxmint/Cinnamon/pull/6881 (add icon to Cinnamon-Settings)
* https://github.com/linuxmint/nemo/pull/1598 (fixes most gDrive operations)
* https://github.com/linuxmint/cinnamon-session/pull/99 (properly shut / restart dbus user-session)
* https://github.com/linuxmint/mint-y-icons/pull/37  (a new symlinked icon for online-accounts)

### CODE REVIEW

**Comment by besser82** [comment]
Needs https://github.com/linuxmint/Cinnamon/pull/6881 to work properly.

**Comment by besser82** [comment]
https://github.com/linuxmint/nemo/pull/1598 puts real fun into this…

**Comment by besser82** [comment]
I've checked for functionality on Fedora 26+ and it works without any issues.

**Comment by besser82** [comment]
@leigh123linux Just finished testing with RHEL7 (GTK-3.22 / GOA 3.22) and everythings work smoothly there, too.

**Comment by besser82** [comment]
https://github.com/linuxmint/mint-y-icons/pull/37 gives eye-candy with Mint-Y-Icons.

**Comment by besser82** [comment]
@clefebvre Any thoughts?

**Comment by clefebvre** [comment]
Hi @besser82,

Here's my feedback. As it is I don't think it's a good idea to add GOA support in Cinnamon. It looks completely out of place and pretty much ALPHA to me.

I'll start with the technical issues:

- The requirement in configure.ac is set to 3.21, it should be changed to 3.18.0.

- In the Cinnamon PR, an icon for cs-online-accounts is needed. I noticed you added it to Mint-Y, it's needed in Cinnamon itself as well.

- The C panel doesn't expand properly in the cinnamon-settings window. Should be easy to fix in the UI file, or by embedding the C panel in a Python module in cinnamon-settings.

- Once an account is enabled, say Google... I'm only able to remove it. I'm not sure if it's a bug or a limitation with 3.18, but I can't pin-point which Google services to give access to.

- Removing an account only seems to remove it locally. Access given to the app GNOME isn't removed online. I can reproduce this with Google for instance.

- Facebook doesn't seem to work. Once added it doesn't go into the top list.

Now, onto my real worries:

- There is no indication as to whether or not passwords are saved. As far as I can see, with Google anyhow, a token is saved and thus you don't need to enter them twice. This is important info for users, novice included. That's easily added in CCC.

- There is no indication as to what accounts are for and what apps use them. In a GNOME environment where all apps take advantage of this, it might make sense, in a Cinnamon environment where these apps are 3rd party and often not present on the system it creates confusion.

- The list of online services is hardcoded and so are the app ID and secrets. These apps are named GNOME and they refer to an environment that isn't ours. That makes sense within a GNOME DE, but it doesn't here.

- From a design point of view, I don't understand why this is implemented like this. First, if this is to be used outside of GNOME it should be done cross-DE, not replicated into Cinnamon. So I would prefer an Xapp client rather than a CCC panel. Second, why create a place for online accounts which aren't used by any apps? Or if these are used by one app, why not have that app support the online account directly?

The real question here is... why are we doing this? In what purpose? Is it simply to let people connect to Google Drive with Nemo? Does it encompass other use cases? Can we list them and from there think of the best way to implement solutions for these?

**Comment by clefebvre** [comment]
I'm a bit annoyed because I can see the value of this for Nemo users wanting to connect to Google Drive... or GNOME apps users using Cinnamon (although I'm not really clear on what apps support what services... and I wouldn't mind having that written somewhere for the user to see)....

.. and yet the design is very confusing, because it gives the feeling of something really integrated into the OS (kinda like what you do with your phone) and yet nothing much will work out of the box.

I'm not sure this is good for us long term and we might remove it at some stage, but we've always been pragmatic, and we've got to accept the fact that some of the cases (like mounting google drive) are solved by this and are really tedious without it.

I'm tempted to embed the CCC panel into a python module and add support in Cinnamon, but with a disclaimer.

**Pull request merged**
